# Generated by Django 5.0.4 on 2024-05-07 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='acknowledgement_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 7, 2, 57, 770486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 7, 2, 57, 770486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 7, 2, 57, 770486, tzinfo=datetime.timezone.utc)),
        ),
    ]
