# Generated by Django 5.0.4 on 2024-05-07 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 17, 57, 55, 87669, tzinfo=datetime.timezone.utc)),
        ),
    ]
