# Generated by Django 5.0.4 on 2024-05-07 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 18, 6, 43, 662398, tzinfo=datetime.timezone.utc)),
        ),
    ]
