# Generated by Django 5.0.4 on 2024-05-09 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 12, 2, 24, 534784, tzinfo=datetime.timezone.utc)),
        ),
    ]
