# Generated by Django 5.0.4 on 2024-05-09 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 12, 3, 9, 53928, tzinfo=datetime.timezone.utc)),
        ),
    ]
