# Generated by Django 5.0.4 on 2024-05-11 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_purchaseorder_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 11, 58, 46, 289581, tzinfo=datetime.timezone.utc)),
        ),
    ]
