# Generated by Django 5.0.4 on 2024-05-13 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 9, 2, 41, 801513, tzinfo=datetime.timezone.utc)),
        ),
    ]
