# Generated by Django 5.0.4 on 2024-05-13 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vendor_password_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 9, 23, 11, 989423, tzinfo=datetime.timezone.utc)),
        ),
    ]
